ukupgrade: New echo's and download error detect
Add error detect (and script stopper) because 4.4 build not have header/image uploaded

diff --git a/ukupgrade b/ukupgrade
--- a/ukupgrade
+++ b/ukupgrade
@@ -4,6 +4,9 @@
 # @mail mustafa.hasturk@yandex.com
 # @link https://github.com/muhasturk/ukupgrade
 
+echo
+echo "Ubuntu Kernel Upgrade"
+
 cd /tmp
 
 if ! which lynx > /dev/null; then sudo apt-get install lynx -y; fi
@@ -12,40 +15,40 @@ if [ "$(getconf LONG_BIT)" == "64" ]; then arch=amd64; else arch=i386; fi
 
 function download() {
    wget $(lynx -dump -listonly -dont-wrap-pre $kernelURL | grep "$1" | grep "$2" | grep "$arch" | cut -d ' ' -f 4)
+   checkdownload=`echo $?`
+   if [ "$checkdownload" == "1" ]; then echo "Download failed!"; exit; fi
 }
 
 # Kernel URL
-read -p "Do you want the latest RC? (y/n): " rc
+read -p "Do you want the latest ReleaseCandidate [RC]? (y/n): " -n 1 -s rc
 case "$rc" in
-   y* | Y*) kernelURL=$(lynx -dump -nonumbers http://kernel.ubuntu.com/~kernel-ppa/mainline/ | tail -1) ;;
-   n* | N*) kernelURL=$(lynx -dump -nonumbers http://kernel.ubuntu.com/~kernel-ppa/mainline/ | grep -v rc | tail -1) ;;
+   y | Y) echo "$rc - ReleaseCandidate"; kernelURL=$(lynx -dump -nonumbers http://kernel.ubuntu.com/~kernel-ppa/mainline/ | tail -1) ;;
+   n | N) echo "$rc - Non ReleaseCandidate"; kernelURL=$(lynx -dump -nonumbers http://kernel.ubuntu.com/~kernel-ppa/mainline/ | grep -v rc | tail -1) ;;
    *) exit ;;
 esac
- 
-read -p "Do you want the lowlatency kernel? (y/n): " lowlatency
-case "$lowlatency" in
-   y* | Y*) lowlatency=1 ;;
-   n* | n*) lowlatency=0 ;;
+
+read -p "Do you want the lowlatency kernel? (y/n): " -n 1 -s km
+case "$km" in
+   y | Y) echo "$km - LowLatency"; kernelmode="lowlatency" ;;
+   n | n) echo "$km - Generic"; kernelmode="generic" ;;
    *) exit ;;
 esac
 
 # Download Kernel
-if [ "$lowlatency" == "0" ]; then
-   echo "Downloading the latest generic kernel...\n"
-   download generic header
-   download generic image
-elif [ "$lowlatency" == "1" ]; then
-   echo "Downloading the latest lowlatency kernel...\n"
-   download lowlatency header
-   download lowlatency image
-fi
+echo "Downloading the latest $kernelmode kernel header..."
+download $km header
+echo "Downloading the latest $kernelmode kernel image..."
+download $km image
 
 # Shared Kernel Header
-echo "Downloading the shared kernel header...\n"
+echo "Downloading the shared kernel header..."
 wget $(lynx -dump -listonly -dont-wrap-pre $kernelURL | grep all | cut -d ' ' -f 4)
+checkdownload=`echo $?`
+if [ "$checkdownload" == "1" ]; then echo "Download failed!"; exit; fi
 
 # Install Kernel
-echo "Installing Linux Kernel...\m"
+echo "Installing Linux Kernel..."
 sudo dpkg -i linux*.deb
+
 echo "Done. We should reboot the machine."
 sudo reboot
